# Generated by Django 5.0.4 on 2024-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=10, max_length=30),
            preserve_default=False,
        ),
    ]
